<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_product_manager"
 *
 * Auto generated by Extension Builder 2014-07-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['pxa_product_manager'] = [
    'title' => 'Product Manager',
    'description' => 'Create and list products on a site.',
    'category' => 'plugin',
    'author' => 'Pixelant',
    'author_email' => 'info@pixelant.net',
    'author_company' => 'Pixelant',
    'state' => 'alpha',
    'createDirs' => '',
    'clearCacheOnLoad' => true,
    'version' => '10.0.0-dev',
    'constraints' => [
        'depends' => [
            'typo3' => '10.0.0-10.0.99'
        ],
        'conflicts' => [],
        'suggests' => []
    ]
];
